services:
  server:
    build: ./server
    ports:
      - "3000:3000"
    env_file: ./server/.env
    environment:
      - NODE_ENV=production

  web:
    build: ./web
    ports:
      - "4000:3000"
    env_file: ./web/.env
    depends_on:
      - server
